name: ipython_notebook_to_html
 
on: workflow_dispatch

jobs:

  build:
 
    runs-on: ubuntu-latest

 
    steps:
 
      - uses: actions/checkout@v3
      
      - name: Install nbconvert
        run: pip install nbconvert
        
      - name: Convert ipynb file to html and drops code cells
        run: jupyter nbconvert --to html --no-input snowpack-obs-comparison-and-trends.ipynb
        
      - name: Add html file to repository
 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "jennifer.f.morse@colorado.edu"
          git config user.name "Jen-Morse"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add --all
          git commit -m "initial commit"
          git push origin HEAD:main
